ALTER TABLE platform.report_revisions
  DROP CONSTRAINT report_revisions_operation_type_check,
  ADD CONSTRAINT report_revisions_operation_type_check CHECK(operation_type IN (
    'REPORT_CREATE','BLOCK_MOVE','BLOCK_RESIZE','BLOCK_CREATE','BLOCK_CLEAR','BLOCK_DELETE','BLOCK_STICKY_UPDATE',
    'COMPONENT_MOVE','COMPONENT_RESIZE','COMPONENT_CREATE','COMPONENT_COPY','COMPONENT_DELETE','COMPONENT_STICKY_UPDATE',
    'LEGACY_DRAFT_RECOVERY','UNDO','REDO'
  ));
