package askdata

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"regexp"
	"sort"
	"strings"
)

const (
	MaxIDLength         = 128
	MaxPolicyDomains    = 64
	MaxPolicyRoles      = 64
	MaxConfidenceProofs = 64
	MaxReasonCodes      = 32
)

var (
	idPattern          = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$`)
	contentHashPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)
	reasonCodePattern  = regexp.MustCompile(`^[A-Z][A-Z0-9_]{0,63}$`)
)

// ID is a stable logical identifier. It may identify a tenant, actor, domain,
// semantic object or immutable object version, but never a physical table or
// column supplied by a user or an LLM.
type ID string

func (id ID) Validate() error {
	if !idPattern.MatchString(string(id)) {
		return fmt.Errorf("invalid stable ID %q", id)
	}
	return nil
}

// ContentHash is a lowercase SHA-256 digest without a prefix.
type ContentHash string

func (hash ContentHash) Validate() error {
	if !contentHashPattern.MatchString(string(hash)) {
		return errors.New("content hash must be 64 lowercase hexadecimal characters")
	}
	return nil
}

// HashBytes returns the immutable SHA-256 reference for a canonical payload.
func HashBytes(payload []byte) ContentHash {
	sum := sha256.Sum256(payload)
	return ContentHash(hex.EncodeToString(sum[:]))
}

// VersionRef pins a logical object to one immutable version and content hash.
type VersionRef struct {
	ObjectID    ID          `json:"objectId"`
	VersionID   ID          `json:"versionId"`
	ContentHash ContentHash `json:"contentHash"`
}

func (ref VersionRef) Validate() error {
	if err := ref.ObjectID.Validate(); err != nil {
		return fmt.Errorf("objectId: %w", err)
	}
	if err := ref.VersionID.Validate(); err != nil {
		return fmt.Errorf("versionId: %w", err)
	}
	if err := ref.ContentHash.Validate(); err != nil {
		return fmt.Errorf("contentHash: %w", err)
	}
	return nil
}

// ReleaseRef pins a question run to one semantic release. A run must not
// silently switch to another release after this reference has been accepted.
type ReleaseRef struct {
	ReleaseID   ID          `json:"releaseId"`
	ContentHash ContentHash `json:"contentHash"`
}

func (ref ReleaseRef) Validate() error {
	if err := ref.ReleaseID.Validate(); err != nil {
		return fmt.Errorf("releaseId: %w", err)
	}
	if err := ref.ContentHash.Validate(); err != nil {
		return fmt.Errorf("contentHash: %w", err)
	}
	return nil
}

// EvidenceKind describes a fact supplied to an LLM decision. Evidence is
// always generated by a trusted component and referenced by ID and hash.
type EvidenceKind string

const (
	EvidenceKindExactAlias       EvidenceKind = "EXACT_ALIAS"
	EvidenceKindLexicalMatch     EvidenceKind = "LEXICAL_MATCH"
	EvidenceKindVectorMatch      EvidenceKind = "VECTOR_MATCH"
	EvidenceKindGraphPath        EvidenceKind = "GRAPH_PATH"
	EvidenceKindSemanticContract EvidenceKind = "SEMANTIC_CONTRACT"
	EvidenceKindCertifiedExample EvidenceKind = "CERTIFIED_EXAMPLE"
	EvidenceKindDimensionProfile EvidenceKind = "DIMENSION_PROFILE"
	EvidenceKindDataQuality      EvidenceKind = "DATA_QUALITY"
	EvidenceKindQueryPlan        EvidenceKind = "QUERY_PLAN"
	EvidenceKindQueryResult      EvidenceKind = "QUERY_RESULT"
	EvidenceKindPolicy           EvidenceKind = "POLICY"
	EvidenceKindRule             EvidenceKind = "RULE"
	EvidenceKindConversation     EvidenceKind = "CONVERSATION"
)

var validEvidenceKinds = map[EvidenceKind]struct{}{
	EvidenceKindExactAlias: {}, EvidenceKindLexicalMatch: {},
	EvidenceKindVectorMatch: {}, EvidenceKindGraphPath: {},
	EvidenceKindSemanticContract: {}, EvidenceKindCertifiedExample: {},
	EvidenceKindDimensionProfile: {}, EvidenceKindDataQuality: {},
	EvidenceKindQueryPlan: {}, EvidenceKindQueryResult: {},
	EvidenceKindPolicy: {}, EvidenceKindRule: {}, EvidenceKindConversation: {},
}

// EvidenceRef is safe to persist. It points to a redacted evidence artifact;
// it does not contain prompts, hidden reasoning, SQL parameters or result rows.
type EvidenceRef struct {
	EvidenceID  ID           `json:"evidenceId"`
	Kind        EvidenceKind `json:"kind"`
	SourceID    ID           `json:"sourceId"`
	ContentHash ContentHash  `json:"contentHash"`
}

func (ref EvidenceRef) Validate() error {
	if err := ref.EvidenceID.Validate(); err != nil {
		return fmt.Errorf("evidenceId: %w", err)
	}
	if _, ok := validEvidenceKinds[ref.Kind]; !ok {
		return fmt.Errorf("unsupported evidence kind %q", ref.Kind)
	}
	if err := ref.SourceID.Validate(); err != nil {
		return fmt.Errorf("sourceId: %w", err)
	}
	if err := ref.ContentHash.Validate(); err != nil {
		return fmt.Errorf("contentHash: %w", err)
	}
	return nil
}

// PolicyScope is the immutable authorization context applied before retrieval,
// before binding and again before execution.
type PolicyScope struct {
	TenantID   ID          `json:"tenantId"`
	ActorID    ID          `json:"actorId"`
	DomainIDs  []ID        `json:"domainIds"`
	RoleIDs    []ID        `json:"roleIds"`
	Release    ReleaseRef  `json:"release"`
	PolicyHash ContentHash `json:"policyHash"`
}

// NewPolicyScope sorts and deduplicates set-valued fields and computes a hash
// that callers can safely include in cache keys and audit records.
func NewPolicyScope(tenantID, actorID ID, domainIDs, roleIDs []ID, release ReleaseRef) (PolicyScope, error) {
	scope := PolicyScope{
		TenantID:  tenantID,
		ActorID:   actorID,
		DomainIDs: normalizedIDs(domainIDs),
		RoleIDs:   normalizedIDs(roleIDs),
		Release:   release,
	}
	if err := scope.validateWithoutHash(); err != nil {
		return PolicyScope{}, err
	}
	hash, err := scopeHash(scope)
	if err != nil {
		return PolicyScope{}, err
	}
	scope.PolicyHash = hash
	return scope, nil
}

func (scope PolicyScope) Validate() error {
	if err := scope.validateWithoutHash(); err != nil {
		return err
	}
	if !equalIDs(scope.DomainIDs, normalizedIDs(scope.DomainIDs)) {
		return errors.New("domainIds must be sorted and unique")
	}
	if !equalIDs(scope.RoleIDs, normalizedIDs(scope.RoleIDs)) {
		return errors.New("roleIds must be sorted and unique")
	}
	if err := scope.PolicyHash.Validate(); err != nil {
		return fmt.Errorf("policyHash: %w", err)
	}
	expected, err := scopeHash(scope)
	if err != nil {
		return err
	}
	if scope.PolicyHash != expected {
		return errors.New("policyHash does not match the policy scope")
	}
	return nil
}

func (scope PolicyScope) validateWithoutHash() error {
	if err := scope.TenantID.Validate(); err != nil {
		return fmt.Errorf("tenantId: %w", err)
	}
	if err := scope.ActorID.Validate(); err != nil {
		return fmt.Errorf("actorId: %w", err)
	}
	if len(scope.DomainIDs) == 0 || len(scope.DomainIDs) > MaxPolicyDomains {
		return fmt.Errorf("domainIds count must be between 1 and %d", MaxPolicyDomains)
	}
	if len(scope.RoleIDs) == 0 || len(scope.RoleIDs) > MaxPolicyRoles {
		return fmt.Errorf("roleIds count must be between 1 and %d", MaxPolicyRoles)
	}
	for index, id := range scope.DomainIDs {
		if err := id.Validate(); err != nil {
			return fmt.Errorf("domainIds[%d]: %w", index, err)
		}
	}
	for index, id := range scope.RoleIDs {
		if err := id.Validate(); err != nil {
			return fmt.Errorf("roleIds[%d]: %w", index, err)
		}
	}
	if err := scope.Release.Validate(); err != nil {
		return fmt.Errorf("release: %w", err)
	}
	return nil
}

func scopeHash(scope PolicyScope) (ContentHash, error) {
	payload := struct {
		TenantID  ID         `json:"tenantId"`
		ActorID   ID         `json:"actorId"`
		DomainIDs []ID       `json:"domainIds"`
		RoleIDs   []ID       `json:"roleIds"`
		Release   ReleaseRef `json:"release"`
	}{scope.TenantID, scope.ActorID, scope.DomainIDs, scope.RoleIDs, scope.Release}
	raw, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal policy scope: %w", err)
	}
	return HashBytes(raw), nil
}

// ConfidenceEvidence records a calibrated score and the facts used by the
// calibrator. Score and margin are system-computed, never trusted from an LLM.
type ConfidenceEvidence struct {
	Score       float64       `json:"score"`
	Margin      float64       `json:"margin"`
	Evidence    []EvidenceRef `json:"evidence"`
	ReasonCodes []string      `json:"reasonCodes"`
}

func (confidence ConfidenceEvidence) Validate() error {
	if !finiteUnitInterval(confidence.Score) {
		return errors.New("score must be a finite number between 0 and 1")
	}
	if !finiteUnitInterval(confidence.Margin) {
		return errors.New("margin must be a finite number between 0 and 1")
	}
	if len(confidence.Evidence) == 0 || len(confidence.Evidence) > MaxConfidenceProofs {
		return fmt.Errorf("evidence count must be between 1 and %d", MaxConfidenceProofs)
	}
	seenEvidence := make(map[ID]struct{}, len(confidence.Evidence))
	for index, evidence := range confidence.Evidence {
		if err := evidence.Validate(); err != nil {
			return fmt.Errorf("evidence[%d]: %w", index, err)
		}
		if _, exists := seenEvidence[evidence.EvidenceID]; exists {
			return fmt.Errorf("evidence[%d] duplicates evidenceId %q", index, evidence.EvidenceID)
		}
		seenEvidence[evidence.EvidenceID] = struct{}{}
	}
	if len(confidence.ReasonCodes) == 0 || len(confidence.ReasonCodes) > MaxReasonCodes {
		return fmt.Errorf("reasonCodes count must be between 1 and %d", MaxReasonCodes)
	}
	seenReasons := make(map[string]struct{}, len(confidence.ReasonCodes))
	for index, code := range confidence.ReasonCodes {
		if !reasonCodePattern.MatchString(code) {
			return fmt.Errorf("reasonCodes[%d] is invalid", index)
		}
		if _, exists := seenReasons[code]; exists {
			return fmt.Errorf("reasonCodes[%d] is duplicated", index)
		}
		seenReasons[code] = struct{}{}
	}
	return nil
}

func finiteUnitInterval(value float64) bool {
	return !math.IsNaN(value) && !math.IsInf(value, 0) && value >= 0 && value <= 1
}

func normalizedIDs(values []ID) []ID {
	seen := make(map[ID]struct{}, len(values))
	result := make([]ID, 0, len(values))
	for _, value := range values {
		if _, exists := seen[value]; exists {
			continue
		}
		seen[value] = struct{}{}
		result = append(result, value)
	}
	sort.Slice(result, func(i, j int) bool { return strings.Compare(string(result[i]), string(result[j])) < 0 })
	return result
}

func equalIDs(left, right []ID) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}
