#!/usr/bin/env sh
set -eu

role=${1:?usage: run-with-nebula-role.sh api|worker|none command...}
shift
[ "$#" -gt 0 ] || {
  printf 'run-with-nebula-role.sh requires a command\n' >&2
  exit 2
}

case "$role" in
  api)
    ASKDATA_NEBULA_ADDRESSES=${ASKDATA_NEBULA_ADDRESSES:-127.0.0.1:${ASKDATA_NEBULA_PORT:-9669}}
    ASKDATA_NEBULA_USERNAME=${ASKDATA_NEBULA_API_USER:?ASKDATA_NEBULA_API_USER is required}
    ASKDATA_NEBULA_PASSWORD=${ASKDATA_NEBULA_API_PASSWORD:?ASKDATA_NEBULA_API_PASSWORD is required}
    ASKDATA_NEBULA_TLS_ENABLED=${ASKDATA_NEBULA_TLS_ENABLED:-false}
    export ASKDATA_NEBULA_ADDRESSES ASKDATA_NEBULA_USERNAME ASKDATA_NEBULA_PASSWORD \
      ASKDATA_NEBULA_TLS_ENABLED
    ;;
  worker)
    ASKDATA_NEBULA_ADDRESSES=${ASKDATA_NEBULA_ADDRESSES:-127.0.0.1:${ASKDATA_NEBULA_PORT:-9669}}
    ASKDATA_NEBULA_USERNAME=${ASKDATA_NEBULA_WORKER_USER:?ASKDATA_NEBULA_WORKER_USER is required}
    ASKDATA_NEBULA_PASSWORD=${ASKDATA_NEBULA_WORKER_PASSWORD:?ASKDATA_NEBULA_WORKER_PASSWORD is required}
    ASKDATA_NEBULA_TLS_ENABLED=${ASKDATA_NEBULA_TLS_ENABLED:-false}
    export ASKDATA_NEBULA_ADDRESSES ASKDATA_NEBULA_USERNAME ASKDATA_NEBULA_PASSWORD \
      ASKDATA_NEBULA_TLS_ENABLED
    ;;
  none)
    unset ASKDATA_NEBULA_ADDRESSES ASKDATA_NEBULA_SPACE ASKDATA_NEBULA_USERNAME \
      ASKDATA_NEBULA_PASSWORD ASKDATA_NEBULA_TLS_ENABLED
    ;;
  *)
    printf 'unknown NebulaGraph process role: %s\n' "$role" >&2
    exit 2
    ;;
esac

# Canonical deployment credentials are only bootstrap inputs. Long-lived local
# processes receive one generic runtime identity, or no graph access at all.
unset ASKDATA_NEBULA_ROOT_PASSWORD ASKDATA_NEBULA_BOOTSTRAP_ROOT_PASSWORD \
  ASKDATA_NEBULA_API_USER ASKDATA_NEBULA_API_PASSWORD \
  ASKDATA_NEBULA_WORKER_USER ASKDATA_NEBULA_WORKER_PASSWORD \
  ASKDATA_NEBULA_PORT

exec "$@"
